cloud_provider/vsphere/vcenter_master_creds_password: ((vsphere_vcenter_password))
wavefront/enabled/wavefront_token: ((wavefront_token))
uaa/ldap/credentials_password: ((uaa_ldap_password))
pivotal-container-service/pks_tls/certificate: ((pivotal-container-service/pks_tls.certificate))
pivotal-container-service/pks_tls/privatekey: ((pivotal-container-service/pks_tls.private_key))
