tsdb/blackbox_exporter_port: 9115
tsdb/scrape_interval: 15s
ui/enable_login_form: true
smoke-test_post_deploy_state: default
update-admin-password_post_deploy_state: default
pxc-proxy_instance_type: automatic
pxc-proxy_instances: automatic
pxc-proxy_persistent_disk_size: automatic
pxc_instance_type: automatic
pxc_instances: automatic
pxc_persistent_disk_size: automatic
tsdb_instance_type: automatic
tsdb_persistent_disk_size: automatic
ui_instance_type: automatic
ui_instances: automatic
ui_persistent_disk_size: automatic
