ui/ssl_certificates/certificate: ((rv_ui/tls.certificate))
ui/ssl_certificates/privatekey: ((rv_ui/tls.private_key))
ui/ssl_ca_certificate: ((rv_ui/tls.ca))

scrape_configs_0/certificate: ((east-pas-exporter-mtls.certificate))
scrape_configs_0/ca: ((east-pas-exporter-mtls.ca))
scrape_configs_0/privatekey: ((east-pas-exporter-mtls.private_key))

scrape_configs_1/certificate: ((west-pas-exporter-mtls.certificate))
scrape_configs_1/ca: ((west-pas-exporter-mtls.ca))
scrape_configs_1/privatekey: ((west-pas-exporter-mtls.private_key))
