errand-config:
  smoke-test:
    post-deploy-state: ((smoke-test_post_deploy_state))
  update-admin-password:
    post-deploy-state: ((update-admin-password_post_deploy_state))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  - name: ((az2_name))
  - name: ((az3_name))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-name: p-reliability-view
product-properties:
  .properties.scrape_configs:
    value:
    - ca: ((scrape_configs_0/ca))
      scrape_job: ((scrape_configs_0/scrape_job))
      server_name: ((scrape_configs_0/server_name))
      tls_certificates:
        cert_pem: ((scrape_configs_0/certificate))
        private_key_pem: ((scrape_configs_0/privatekey))
  .properties.smtp:
    value: disabled
  .properties.ui_authentication:
    value: basic
  .tsdb.blackbox_exporter_port:
    value: ((tsdb/blackbox_exporter_port))
  .tsdb.scrape_interval:
    value: ((tsdb/scrape_interval))
  .ui.enable_login_form:
    value: ((ui/enable_login_form))
  .ui.ssl_ca_certificate:
    value: ((ui/ssl_ca_certificate))
  .ui.ssl_certificates:
    value:
      cert_pem: ((ui/ssl_certificates/certificate))
      private_key_pem: ((ui/ssl_certificates/privatekey))
  .ui.ui_root_url:
    value: ((ui/ui_root_url))
resource-config:
  pxc:
    instance_type:
      id: ((pxc_instance_type))
    instances: ((pxc_instances))
    persistent_disk:
      size_mb: ((pxc_persistent_disk_size))
  pxc-proxy:
    instance_type:
      id: ((pxc-proxy_instance_type))
    instances: ((pxc-proxy_instances))
    persistent_disk:
      size_mb: ((pxc-proxy_persistent_disk_size))
  tsdb:
    instance_type:
      id: ((tsdb_instance_type))
    persistent_disk:
      size_mb: ((tsdb_persistent_disk_size))
  ui:
    additional_vm_extensions: ((ui_additional_vm_extensions))
    elb_names: ((ui_elb_names))
    instance_type:
      id: ((ui_instance_type))
    instances: ((ui_instances))
    persistent_disk:
      size_mb: ((ui_persistent_disk_size))
