ui/ssl_certificates/certificate: ((rv_ui/tls.certificate))
ui/ssl_certificates/privatekey: ((rv_ui/tls.private_key))

scrape_configs_0/certificate: ((east-pas-exporter-mtls.certificate))
scrape_configs_0/ca: ((east-pas-exporter-mtls.ca))
scrape_configs_0/privatekey: ((east-pas-exporter-mtls.private_key))
