credhub_key_encryption_passwords_0/key: ((properties_credhub_key_encryption_passwords_0_key_secret))
networking_poe_ssl_certs_0/certificate: ((cf/networking_poe_ssl_certs_0_certificate.certificate))
networking_poe_ssl_certs_0/privatekey: ((cf/networking_poe_ssl_certs_0_certificate.private_key))
uaa/service_provider_key_credentials/certificate: ((cf/uaa_service_provider_key_credentials.certificate))
uaa/service_provider_key_credentials/privatekey: ((cf/uaa_service_provider_key_credentials.private_key))
uaa/ldap/credentials_password: ((uaa_ldap_password))
